// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220929.3

#pragma once
#ifndef WINRT_ModalessDialog_0_H
#define WINRT_ModalessDialog_0_H
WINRT_EXPORT namespace winrt::Microsoft::UI::Xaml::Markup
{
    struct IXamlMetadataProvider;
}
WINRT_EXPORT namespace winrt::ModalessDialog
{
    struct IDialog;
    struct IMainWindow;
    struct Dialog;
    struct MainWindow;
    struct XamlMetaDataProvider;
}
namespace winrt::impl
{
    template <> struct category<winrt::ModalessDialog::IDialog>{ using type = interface_category; };
    template <> struct category<winrt::ModalessDialog::IMainWindow>{ using type = interface_category; };
    template <> struct category<winrt::ModalessDialog::Dialog>{ using type = class_category; };
    template <> struct category<winrt::ModalessDialog::MainWindow>{ using type = class_category; };
    template <> struct category<winrt::ModalessDialog::XamlMetaDataProvider>{ using type = class_category; };
    template <> inline constexpr auto& name_v<winrt::ModalessDialog::Dialog> = L"ModalessDialog.Dialog";
    template <> inline constexpr auto& name_v<winrt::ModalessDialog::MainWindow> = L"ModalessDialog.MainWindow";
    template <> inline constexpr auto& name_v<winrt::ModalessDialog::XamlMetaDataProvider> = L"ModalessDialog.XamlMetaDataProvider";
    template <> inline constexpr auto& name_v<winrt::ModalessDialog::IDialog> = L"ModalessDialog.IDialog";
    template <> inline constexpr auto& name_v<winrt::ModalessDialog::IMainWindow> = L"ModalessDialog.IMainWindow";
    template <> inline constexpr guid guid_v<winrt::ModalessDialog::IDialog>{ 0x061A7D96,0x6E95,0x5710,{ 0x96,0x88,0x2A,0x20,0x85,0x77,0xCF,0x22 } }; // 061A7D96-6E95-5710-9688-2A208577CF22
    template <> inline constexpr guid guid_v<winrt::ModalessDialog::IMainWindow>{ 0x18E12186,0x7154,0x58C4,{ 0xBC,0x4D,0x31,0xA3,0x98,0xAA,0xA5,0x6F } }; // 18E12186-7154-58C4-BC4D-31A398AAA56F
    template <> struct default_interface<winrt::ModalessDialog::Dialog>{ using type = winrt::ModalessDialog::IDialog; };
    template <> struct default_interface<winrt::ModalessDialog::MainWindow>{ using type = winrt::ModalessDialog::IMainWindow; };
    template <> struct default_interface<winrt::ModalessDialog::XamlMetaDataProvider>{ using type = winrt::Microsoft::UI::Xaml::Markup::IXamlMetadataProvider; };
    template <> struct abi<winrt::ModalessDialog::IDialog>
    {
        struct __declspec(novtable) type : inspectable_abi
        {
            virtual int32_t __stdcall get_MyProperty(int32_t*) noexcept = 0;
            virtual int32_t __stdcall put_MyProperty(int32_t) noexcept = 0;
        };
    };
    template <> struct abi<winrt::ModalessDialog::IMainWindow>
    {
        struct __declspec(novtable) type : inspectable_abi
        {
            virtual int32_t __stdcall get_MyProperty(int32_t*) noexcept = 0;
            virtual int32_t __stdcall put_MyProperty(int32_t) noexcept = 0;
        };
    };
    template <typename D>
    struct consume_ModalessDialog_IDialog
    {
        [[nodiscard]] auto MyProperty() const;
        auto MyProperty(int32_t value) const;
    };
    template <> struct consume<winrt::ModalessDialog::IDialog>
    {
        template <typename D> using type = consume_ModalessDialog_IDialog<D>;
    };
    template <typename D>
    struct consume_ModalessDialog_IMainWindow
    {
        [[nodiscard]] auto MyProperty() const;
        auto MyProperty(int32_t value) const;
    };
    template <> struct consume<winrt::ModalessDialog::IMainWindow>
    {
        template <typename D> using type = consume_ModalessDialog_IMainWindow<D>;
    };
}
#endif
