// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220929.3

#pragma once
#include "winrt/Microsoft.UI.Xaml.h"
#include "winrt/ModalessDialog.h"
namespace winrt::ModalessDialog::implementation
{
    template <typename D, typename... I>
    struct __declspec(empty_bases) Dialog_base : implements<D, ModalessDialog::Dialog, composing, I...>,
        impl::require<D, winrt::Microsoft::UI::Xaml::IWindow, winrt::Microsoft::UI::Xaml::IWindow2>,
        impl::base<D, winrt::Microsoft::UI::Xaml::Window>
    {
        using base_type = Dialog_base;
        using class_type = ModalessDialog::Dialog;
        using implements_type = typename Dialog_base::implements_type;
        using implements_type::implements_type;
        using composable_base = winrt::Microsoft::UI::Xaml::Window;
        hstring GetRuntimeClassName() const
        {
            return L"ModalessDialog.Dialog";
        }
        Dialog_base()
        {
            impl::call_factory<winrt::Microsoft::UI::Xaml::Window, winrt::Microsoft::UI::Xaml::IWindowFactory>([&](winrt::Microsoft::UI::Xaml::IWindowFactory const& f) { [[maybe_unused]] auto winrt_impl_discarded = f.CreateInstance(*this, this->m_inner); });
        }
    };
}
namespace winrt::ModalessDialog::factory_implementation
{
    template <typename D, typename T, typename... I>
    struct __declspec(empty_bases) DialogT : implements<D, winrt::Windows::Foundation::IActivationFactory, I...>
    {
        using instance_type = ModalessDialog::Dialog;

        hstring GetRuntimeClassName() const
        {
            return L"ModalessDialog.Dialog";
        }
        auto ActivateInstance() const
        {
            return make<T>();
        }
    };
}

#if defined(WINRT_FORCE_INCLUDE_DIALOG_XAML_G_H) || __has_include("Dialog.xaml.g.h")

#include "Dialog.xaml.g.h"

#else

namespace winrt::ModalessDialog::implementation
{
    template <typename D, typename... I>
    using DialogT = Dialog_base<D, I...>;
}

#endif
