// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220929.3

void* winrt_make_ModalessDialog_Dialog()
{
    return winrt::detach_abi(winrt::make<winrt::ModalessDialog::factory_implementation::Dialog>());
}
WINRT_EXPORT namespace winrt::ModalessDialog
{
    Dialog::Dialog() :
        Dialog(make<ModalessDialog::implementation::Dialog>())
    {
    }
}
