// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220929.3

void* winrt_make_ModalessDialog_MainWindow()
{
    return winrt::detach_abi(winrt::make<winrt::ModalessDialog::factory_implementation::MainWindow>());
}
WINRT_EXPORT namespace winrt::ModalessDialog
{
    MainWindow::MainWindow() :
        MainWindow(make<ModalessDialog::implementation::MainWindow>())
    {
    }
}
