namespace GridStyleListView
{
    runtimeclass Data : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        Data(String name, String service);

        String Name;
        String Service;
    }
}